name = "kimpure/globrex_lune"
description = "glob to regular expression compiler."
repository = "https://github.com/kimpure/globrex-lune"
version = "0.2.2"
authors = ["kimpure (sunwoo)"]
license = "MIT"
includes = ["src", "README.md", "LICENSE.md", "pesde.toml"]

[target]
environment = "lune"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
luau_regexp = { name = "jiwonz/luau_regexp", version = "^0.1.0", target = "luau" }

[dev_dependencies]
luau_check = { name = "jiwonz/luau_check", version = "^0.2.2" }
selene = { name = "pesde/selene", version = "^0.27.1" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.38.1" }
stylua = { name = "pesde/stylua", version = "^2.0.2" }
