name = "kimpure/globrex_lune"
description = "glob to regular expression compiler."
authors = ["sunwoo"]
version = "0.1.0"
repository = "https://github.com/kimpure/globrex-lune"
license = "MIT"
includes = ["init.luau", "pesde.toml", "README.md", "LICENSE.md"]

[target]
environment = "lune"
lib = "init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
luau_regexp = { name = "jiwonz/luau_regexp", version = "^0.1.0", target = "luau" }